# Generated by Django 3.2.2 on 2021-06-09 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spotify', '0002_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='votes',
            name='current_song',
        ),
    ]
